[settings]
python.uv_venv_auto = true
python.default_packages_file = "~/.default-python-packages"
idiomatic_version_file_enable_tools = ["python", "node"]
disable_backends = [ "pipx" ]
experimental = true

[tools]
chezmoi = {version="latest", postinstall="chezmoi completion zsh --output ~/.config/zsh/completions/_chezmoi"}
golang = "latest"
python = "latest"
uv = {version="latest", postinstall="uv generate-shell-completion zsh > ~/.config/zsh/completions/_uv"}
rust = "stable"
node = "lts"
bun = "latest"
lua-language-server = "latest"
shellcheck = "latest"
shfmt = "latest"
usage = "latest"
jq = "latest"
qsv = "latest"
gh = "latest"
rclone = "latest"
1password = "latest"
task = {version="latest", postinstall="task --completion > ~/.config/zsh/completions/_task"}
neovim = "0.11.6"
restic = "latest"

# system tools
"aqua:BurntSushi/ripgrep" = {version="latest", postinstall="rg complete-zsh > ~/.config/zsh/completions/_rg"}
"aqua:ClementTsang/bottom" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:starship/starship" = "latest"
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:dandavison/delta" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:ducaale/xh" = {version="latest", postinstall="xh --generate zsh > ~/.config/zsh/completions/_xh"}
"aqua:tree-sitter/tree-sitter" = "latest"
"cargo:xan" = {version="latest", postinstall="xan completions zsh > ~/.config/zsh/completions/_xan"}
"aqua:aws/aws-cli" = "latest"
claude = { version = "latest", bin = "claude", platforms = """
[linux-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/linux-arm64/claude"

[linux-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/linux-x64/claude"

[macos-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/darwin-arm64/claude"

[macos-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/darwin-x64/claude"
""", version_list_url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/stable" }
"github:anomalyco/opencode" = "latest"
"aqua:peteretelej/tree" = "latest"
codex = "latest"
